import type { Metadata } from "next";
import { Montserrat, Forum, Six_Caps} from "next/font/google";
import { FloatingNav } from "@/components/ui/layout/Header";
import "./globals.css";
import ReactLenis from 'lenis/react'






export const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
});
export const BarlowCondensed = Six_Caps ({
  subsets: ['latin'],
  variable: '--Barlow-Condensed',
  display: 'swap',
 weight: "400"
});
export const forum = Forum({
  subsets: ['latin'],
  variable: '--font-forum',
  display: 'swap',
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.variable} ${forum.variable}  ${BarlowCondensed.variable} font-montserrat dark  antialiased`}
      >
        <ReactLenis root>
        <FloatingNav      />
        {children}
     </ReactLenis>
      </body>
    </html>
  );
}
